In [140]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

In [141]:
df = pd.read_csv(r'C:\CODING\MACHINE LEARNING\data.csv')

## EDA

In [142]:
df.head()

,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,sqft_above,sqft_basement,yr_built,yr_renovated,street,city,statezip,country
0,2014-05-02 00:00:00,313000.0,3.0,1.50,1340,7912,1.5,0,0,3,1340,0,1955,2005,18810 Densmore Ave N,Shoreline,WA 98133,USA
1,2014-05-02 00:00:00,2384000.0,5.0,2.50,3650,9050,2.0,0,4,5,3370,280,1921,0,709 W Blaine St,Seattle,WA 98119,USA
2,2014-05-02 00:00:00,342000.0,3.0,2.00,1930,11947,1.0,0,0,4,1930,0,1966,0,26206-26214 143rd Ave SE,Kent,WA 98042,USA
3,2014-05-02 00:00:00,420000.0,3.0,2.25,2000,8030,1.0,0,0,4,1000,1000,1963,0,857 170th Pl NE,Bellevue,WA 98008,USA
4,2014-05-02 00:00:00,550000.0,4.0,2.50,1940,10500,1.0,0,0,4,1140,800,1976,1992,9105 170th Ave NE,Redmond,WA 98052,USA

In [143]:
df.shape

(4600, 18)

In [144]:
df.describe()

,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,sqft_above,sqft_basement,yr_built,yr_renovated
count,4.600000e+03,4600.000000,4600.000000,4600.000000,4.600000e+03,4600.000000,4600.000000,4600.000000,4600.000000,4600.000000,4600.000000,4600.000000,4600.000000
mean,5.519630e+05,3.400870,2.160815,2139.346957,1.485252e+04,1.512065,0.007174,0.240652,3.451739,1827.265435,312.081522,1970.786304,808.608261
std,5.638347e+05,0.908848,0.783781,963.206916,3.588444e+04,0.538288,0.084404,0.778405,0.677230,862.168977,464.137228,29.731848,979.414536
min,0.000000e+00,0.000000,0.000000,370.000000,6.380000e+02,1.000000,0.000000,0.000000,1.000000,370.000000,0.000000,1900.000000,0.000000
25%,3.228750e+05,3.000000,1.750000,1460.000000,5.000750e+03,1.000000,0.000000,0.000000,3.000000,1190.000000,0.000000,1951.000000,0.000000
50%,4.609435e+05,3.000000,2.250000,1980.000000,7.683000e+03,1.500000,0.000000,0.000000,3.000000,1590.000000,0.000000,1976.000000,0.000000
75%,6.549625e+05,4.000000,2.500000,2620.000000,1.100125e+04,2.000000,0.000000,0.000000,4.000000,2300.000000,610.000000,1997.000000,1999.000000
max,2.659000e+07,9.000000,8.000000,13540.000000,1.074218e+06,3.500000,1.000000,4.000000,5.000000,9410.000000,4820.000000,2014.000000,2014.000000

In [145]:
df.isnull().sum()

date             0
price            0
bedrooms         0
bathrooms        0
sqft_living      0
sqft_lot         0
floors           0
waterfront       0
view             0
condition        0
sqft_above       0
sqft_basement    0
yr_built         0
yr_renovated     0
street           0
city             0
statezip         0
country          0
dtype: int64

In [146]:
df.duplicated().sum()

np.int64(0)

In [147]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4600 entries, 0 to 4599
Data columns (total 18 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   date           4600 non-null   str
 1   price          4600 non-null   float64
 2   bedrooms       4600 non-null   float64
 3   bathrooms      4600 non-null   float64
 4   sqft_living    4600 non-null   int64
 5   sqft_lot       4600 non-null   int64
 6   floors         4600 non-null   float64
 7   waterfront     4600 non-null   int64
 8   view           4600 non-null   int64
 9   condition      4600 non-null   int64
 10  sqft_above     4600 non-null   int64
 11  sqft_basement  4600 non-null   int64
 12  yr_built       4600 non-null   int64
 13  yr_renovated   4600 non-null   int64
 14  street         4600 non-null   str
 15  city           4600 non-null   str
 16  statezip       4600 non-null   str
 17  country        4600 non-null   str
dtypes: float64(4), int64(9), str(5)
memory usage: 647.0 KB

## droping something that we dont need

In [148]:
df = df.drop(['date'],axis=1)

In [149]:
df.head()

,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,sqft_above,sqft_basement,yr_built,yr_renovated,street,city,statezip,country
0,313000.0,3.0,1.50,1340,7912,1.5,0,0,3,1340,0,1955,2005,18810 Densmore Ave N,Shoreline,WA 98133,USA
1,2384000.0,5.0,2.50,3650,9050,2.0,0,4,5,3370,280,1921,0,709 W Blaine St,Seattle,WA 98119,USA
2,342000.0,3.0,2.00,1930,11947,1.0,0,0,4,1930,0,1966,0,26206-26214 143rd Ave SE,Kent,WA 98042,USA
3,420000.0,3.0,2.25,2000,8030,1.0,0,0,4,1000,1000,1963,0,857 170th Pl NE,Bellevue,WA 98008,USA
4,550000.0,4.0,2.50,1940,10500,1.0,0,0,4,1140,800,1976,1992,9105 170th Ave NE,Redmond,WA 98052,USA

In [150]:
df['street'].value_counts()

street
2520 Mulberry Walk NE    4
2500 Mulberry Walk NE    3
Burke-Gilman Trail       2
23017 SE 281st Ct        2
35229 SE Terrace St      2
                        ..
501 N 143rd St           1
14855 SE 10th Pl         1
759 Ilwaco Pl NE         1
5148 S Creston St        1
18717 SE 258th St        1
Name: count, Length: 4525, dtype: int64

In [151]:
x = df.drop(['price'], axis = 1)
y = df['price']

In [152]:
x

,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,sqft_above,sqft_basement,yr_built,yr_renovated,street,city,statezip,country
0,3.0,1.50,1340,7912,1.5,0,0,3,1340,0,1955,2005,18810 Densmore Ave N,Shoreline,WA 98133,USA
1,5.0,2.50,3650,9050,2.0,0,4,5,3370,280,1921,0,709 W Blaine St,Seattle,WA 98119,USA
2,3.0,2.00,1930,11947,1.0,0,0,4,1930,0,1966,0,26206-26214 143rd Ave SE,Kent,WA 98042,USA
3,3.0,2.25,2000,8030,1.0,0,0,4,1000,1000,1963,0,857 170th Pl NE,Bellevue,WA 98008,USA
4,4.0,2.50,1940,10500,1.0,0,0,4,1140,800,1976,1992,9105 170th Ave NE,Redmond,WA 98052,USA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4595,3.0,1.75,1510,6360,1.0,0,0,4,1510,0,1954,1979,501 N 143rd St,Seattle,WA 98133,USA
4596,3.0,2.50,1460,7573,2.0,0,0,3,1460,0,1983,2009,14855 SE 10th Pl,Bellevue,WA 98007,USA
4597,3.0,2.50,3010,7014,2.0,0,0,3,3010,0,2009,0,759 Ilwaco Pl NE,Renton,WA 98059,USA
4598,4.0,2.00,2090,6630,1.0,0,0,3,1070,1020,1974,0,5148 S Creston St,Seattle,WA 98178,USA
4599,3.0,2.50,1490,8102,2.0,0,0,4,1490,0,1990,0,18717 SE 258th St,Covington,WA 98042,USA

In [153]:
y

0       3.130000e+05
1       2.384000e+06
2       3.420000e+05
3       4.200000e+05
4       5.500000e+05
            ...
4595    3.081667e+05
4596    5.343333e+05
4597    4.169042e+05
4598    2.034000e+05
4599    2.206000e+05
Name: price, Length: 4600, dtype: float64

In [154]:
df.columns

Index(['price', 'bedrooms', 'bathrooms', 'sqft_living', 'sqft_lot', 'floors',
       'waterfront', 'view', 'condition', 'sqft_above', 'sqft_basement',
       'yr_built', 'yr_renovated', 'street', 'city', 'statezip', 'country'],
      dtype='str')

In [155]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4600 entries, 0 to 4599
Data columns (total 17 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   price          4600 non-null   float64
 1   bedrooms       4600 non-null   float64
 2   bathrooms      4600 non-null   float64
 3   sqft_living    4600 non-null   int64
 4   sqft_lot       4600 non-null   int64
 5   floors         4600 non-null   float64
 6   waterfront     4600 non-null   int64
 7   view           4600 non-null   int64
 8   condition      4600 non-null   int64
 9   sqft_above     4600 non-null   int64
 10  sqft_basement  4600 non-null   int64
 11  yr_built       4600 non-null   int64
 12  yr_renovated   4600 non-null   int64
 13  street         4600 non-null   str
 14  city           4600 non-null   str
 15  statezip       4600 non-null   str
 16  country        4600 non-null   str
dtypes: float64(4), int64(9), str(4)
memory usage: 611.1 KB

## DOING ONE_HOT_ENCODING TO CONVERT STR INTO NUMERIC

In [156]:
one_hot_encoding = pd.get_dummies(x,columns=['street', 'city', 'statezip', 'country'],drop_first=True)

In [157]:
one_hot_encoding.head()

,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,sqft_above,sqft_basement,...,statezip_WA 98155,statezip_WA 98166,statezip_WA 98168,statezip_WA 98177,statezip_WA 98178,statezip_WA 98188,statezip_WA 98198,statezip_WA 98199,statezip_WA 98288,statezip_WA 98354
0,3.0,1.50,1340,7912,1.5,0,0,3,1340,0,...,False,False,False,False,False,False,False,False,False,False
1,5.0,2.50,3650,9050,2.0,0,4,5,3370,280,...,False,False,False,False,False,False,False,False,False,False
2,3.0,2.00,1930,11947,1.0,0,0,4,1930,0,...,False,False,False,False,False,False,False,False,False,False
3,3.0,2.25,2000,8030,1.0,0,0,4,1000,1000,...,False,False,False,False,False,False,False,False,False,False
4,4.0,2.50,1940,10500,1.0,0,0,4,1140,800,...,False,False,False,False,False,False,False,False,False,False

In [158]:
one_hot_encoding=one_hot_encoding.astype(int)

In [159]:
one_hot_encoding.head()

,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,sqft_above,sqft_basement,...,statezip_WA 98155,statezip_WA 98166,statezip_WA 98168,statezip_WA 98177,statezip_WA 98178,statezip_WA 98188,statezip_WA 98198,statezip_WA 98199,statezip_WA 98288,statezip_WA 98354
0,3,1,1340,7912,1,0,0,3,1340,0,...,0,0,0,0,0,0,0,0,0,0
1,5,2,3650,9050,2,0,4,5,3370,280,...,0,0,0,0,0,0,0,0,0,0
2,3,2,1930,11947,1,0,0,4,1930,0,...,0,0,0,0,0,0,0,0,0,0
3,3,2,2000,8030,1,0,0,4,1000,1000,...,0,0,0,0,0,0,0,0,0,0
4,4,2,1940,10500,1,0,0,4,1140,800,...,0,0,0,0,0,0,0,0,0,0

In [160]:
one_hot_encoding.info()

<class 'pandas.DataFrame'>
RangeIndex: 4600 entries, 0 to 4599
Columns: 4655 entries, bedrooms to statezip_WA 98354
dtypes: int64(4655)
memory usage: 163.4 MB

In [161]:
one_hot_encoding

,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,sqft_above,sqft_basement,...,statezip_WA 98155,statezip_WA 98166,statezip_WA 98168,statezip_WA 98177,statezip_WA 98178,statezip_WA 98188,statezip_WA 98198,statezip_WA 98199,statezip_WA 98288,statezip_WA 98354
0,3,1,1340,7912,1,0,0,3,1340,0,...,0,0,0,0,0,0,0,0,0,0
1,5,2,3650,9050,2,0,4,5,3370,280,...,0,0,0,0,0,0,0,0,0,0
2,3,2,1930,11947,1,0,0,4,1930,0,...,0,0,0,0,0,0,0,0,0,0
3,3,2,2000,8030,1,0,0,4,1000,1000,...,0,0,0,0,0,0,0,0,0,0
4,4,2,1940,10500,1,0,0,4,1140,800,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4595,3,1,1510,6360,1,0,0,4,1510,0,...,0,0,0,0,0,0,0,0,0,0
4596,3,2,1460,7573,2,0,0,3,1460,0,...,0,0,0,0,0,0,0,0,0,0
4597,3,2,3010,7014,2,0,0,3,3010,0,...,0,0,0,0,0,0,0,0,0,0
4598,4,2,2090,6630,1,0,0,3,1070,1020,...,0,0,0,0,1,0,0,0,0,0
4599,3,2,1490,8102,2,0,0,4,1490,0,...,0,0,0,0,0,0,0,0,0,0

## PERFOMING LABEL ENCODING

In [162]:
x.columns

Index(['bedrooms', 'bathrooms', 'sqft_living', 'sqft_lot', 'floors',
       'waterfront', 'view', 'condition', 'sqft_above', 'sqft_basement',
       'yr_built', 'yr_renovated', 'street', 'city', 'statezip', 'country'],
      dtype='str')

In [163]:
x

,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,sqft_above,sqft_basement,yr_built,yr_renovated,street,city,statezip,country
0,3.0,1.50,1340,7912,1.5,0,0,3,1340,0,1955,2005,18810 Densmore Ave N,Shoreline,WA 98133,USA
1,5.0,2.50,3650,9050,2.0,0,4,5,3370,280,1921,0,709 W Blaine St,Seattle,WA 98119,USA
2,3.0,2.00,1930,11947,1.0,0,0,4,1930,0,1966,0,26206-26214 143rd Ave SE,Kent,WA 98042,USA
3,3.0,2.25,2000,8030,1.0,0,0,4,1000,1000,1963,0,857 170th Pl NE,Bellevue,WA 98008,USA
4,4.0,2.50,1940,10500,1.0,0,0,4,1140,800,1976,1992,9105 170th Ave NE,Redmond,WA 98052,USA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4595,3.0,1.75,1510,6360,1.0,0,0,4,1510,0,1954,1979,501 N 143rd St,Seattle,WA 98133,USA
4596,3.0,2.50,1460,7573,2.0,0,0,3,1460,0,1983,2009,14855 SE 10th Pl,Bellevue,WA 98007,USA
4597,3.0,2.50,3010,7014,2.0,0,0,3,3010,0,2009,0,759 Ilwaco Pl NE,Renton,WA 98059,USA
4598,4.0,2.00,2090,6630,1.0,0,0,3,1070,1020,1974,0,5148 S Creston St,Seattle,WA 98178,USA
4599,3.0,2.50,1490,8102,2.0,0,0,4,1490,0,1990,0,18717 SE 258th St,Covington,WA 98042,USA

## doing standart  scaling convert large numeric into smaller one with the help of one hot encoding

In [164]:
from sklearn.preprocessing import StandardScaler

In [165]:
numeric_colum = ['bedrooms', 'bathrooms', 'sqft_living', 'sqft_lot', 'floors',
       'waterfront', 'view', 'condition', 'sqft_above', 'sqft_basement',
       'yr_built', 'yr_renovated']

scaler = StandardScaler()

one_hot_encoding[numeric_colum] = scaler.fit_transform(one_hot_encoding[numeric_colum])

In [167]:
one_hot_encoding

,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,sqft_above,sqft_basement,...,statezip_WA 98155,statezip_WA 98166,statezip_WA 98168,statezip_WA 98177,statezip_WA 98178,statezip_WA 98188,statezip_WA 98198,statezip_WA 98199,statezip_WA 98288,statezip_WA 98354
0,-0.441122,-1.048942,-0.829971,-0.193434,-0.831557,-0.085004,-0.309194,-0.667112,-0.565224,-0.672464,...,0,0,0,0,0,0,0,0,0,0
1,1.759705,0.280662,1.568528,-0.161718,0.979599,-0.085004,4.830079,2.286416,1.789559,-0.069128,...,0,0,0,0,0,0,0,0,0,0
2,-0.441122,0.280662,-0.217367,-0.080978,-0.831557,-0.085004,-0.309194,0.809652,0.119171,-0.672464,...,0,0,0,0,0,0,0,0,0,0
3,-0.441122,0.280662,-0.144686,-0.190145,-0.831557,-0.085004,-0.309194,0.809652,-0.959621,1.482306,...,0,0,0,0,0,0,0,0,0,0
4,0.659291,0.280662,-0.206984,-0.121306,-0.831557,-0.085004,-0.309194,0.809652,-0.797222,1.051352,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4595,-0.441122,-1.048942,-0.653458,-0.236689,-0.831557,-0.085004,-0.309194,0.809652,-0.368025,-0.672464,...,0,0,0,0,0,0,0,0,0,0
4596,-0.441122,0.280662,-0.705374,-0.202882,0.979599,-0.085004,-0.309194,-0.667112,-0.426025,-0.672464,...,0,0,0,0,0,0,0,0,0,0
4597,-0.441122,0.280662,0.904009,-0.218462,0.979599,-0.085004,-0.309194,-0.667112,1.371962,-0.672464,...,0,0,0,0,0,0,0,0,0,0
4598,0.659291,0.280662,-0.051238,-0.229164,-0.831557,-0.085004,-0.309194,-0.667112,-0.878421,1.525401,...,0,0,0,0,1,0,0,0,0,0
4599,-0.441122,0.280662,-0.674224,-0.188139,0.979599,-0.085004,-0.309194,0.809652,-0.391225,-0.672464,...,0,0,0,0,0,0,0,0,0,0

## creating model with the help of one_hot_encoding

In [168]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score

In [169]:
X_train, X_test, y_train, y_test = train_test_split(one_hot_encoding, y, test_size=0.33, random_state=42)

In [173]:
model = LinearRegression()
model.fit(X_train,y_train)

LinearRegression()

## doing predection

In [174]:
y_pred = model.predict(X_test)

In [175]:
y_pred

array([  118824.92680056,  -458136.12879888,  3802883.5274358 , ...,
       10671861.50102252,   414413.5179937 ,   756648.72035686],
      shape=(1518,))

In [178]:
y_test

3683     544000.0
4411          0.0
2584    1712500.0
69       365000.0
1844     275000.0
          ...
1299     372000.0
2535     763101.0
4234     450000.0
660      364000.0
2741     403500.0
Name: price, Length: 1518, dtype: float64

In [179]:
r2 = r2_score(y_pred, y_test)

In [180]:
r2

-0.052605306652077743